---
name: CI

on:
  push:
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 17, 18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --immutable
      - run: yarn compile
      - run: yarn lint
      - run: yarn test

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --immutable
      - run: yarn docs
      - uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: |
            **/docs/**
      - name: Fail on missing docs
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "::error::The API reference docs have uncommitted changes:"
          echo "::error::${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1
